### ISSUE TITLE
YAML alias not working

### ISSUE THREAD

**Issue by Art-S-D** [malaval/aws-orga-deployer#2]
When I try to use an alias (as specified in the docs) I get this error:

`CRITICAL The package definition YAML file is invalid - Additional properties are not allowed ('myalias' was unexpected)`

**Comment by Art-S-D** [comment]
Made a pr to fix it https://github.com/malaval/aws-orga-deployer/pull/3

**Comment by malaval** [comment]
Thanks, I merged it.
